variables:
  - &docker_creds
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

steps:
  build:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: edrodefeld/atlas
      auto_tag: true
      <<: *docker_creds
    when:
      - event: [push, manual]
        branch: main

  deploy:
    image: bitnami/kubectl
    commands:
      - kubectl rollout restart deployment/atlas -n galaxy
    when:
      - event: [push, manual]
        branch: main
